server.port=8080
spring.application.name=api-gateway

## Route AUTH SERVICE
#spring.cloud.gateway.server.webflux.routes[0].id=auth-service
#spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8082
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**
## Route TABLE and MENU SERVICE
#spring.cloud.gateway.server.webflux.routes[1].id=table-menu-service
#spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8083
#spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/items/**, /api/v1/upload/**, /api/v1/categories/**, /api/v1/sessions/**, /api/v1/tables/**
## Route Order
#spring.cloud.gateway.server.webflux.routes[2].id=order-service
#spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8084
#spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/orders/**
## Route Kitchen
#spring.cloud.gateway.server.webflux.routes[3].id=kitchen-service
#spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8085
#spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/kitchens/**
## Route WebSocket - Ph?i dùng ws://
#spring.cloud.gateway.server.webflux.routes[4].id=websocket-service
#spring.cloud.gateway.server.webflux.routes[4].uri=ws://localhost:8085
#spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/ws/**
# CORS Configuration - Thêm headers cho WebSocket
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=3600

# JWT
imthang.jwt.base64-secret=LVIe88d1bftZTX8Ykz7TTUd6cR5Q6qL0o0ivPrbot2GBX2YBw9pT2CgGus2aXhHmRYl4NfdMDI7G/hYxBxw33A==
imthang.jwt.access-token-validity-in-seconds=90000
imthang.jwt.refresh-token-validity-in-seconds=90000
spring.main.web-application-type=reactive
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.security=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true